# Generated by Django 5.2.12 on 2026-03-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_watchlist_watchlist_watchlist_listing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='owner',
        ),
    ]
