# Generated by Django 5.2.12 on 2026-04-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist_listing_watchlist_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='listings',
            new_name='listing',
        ),
    ]
