# Generated by Django 5.2.12 on 2026-04-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_watchlist_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Close',
        ),
    ]
